/* Run: PLAYWRIGHT_MODULE=/path/to/playwright node tests/browser.cjs */
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:1080},deviceScaleFactor:1});
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.DEMO_URL || 'http://127.0.0.1:5083');
  await page.locator('#run').click();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '10');
  assert.equal(await page.locator('#rows tr').count(),10);
  assert.match(await page.locator('#summary').textContent(), /3 páginas.*1 duplicados.*1 incompletos/);
  await fs.mkdir('assets/screenshots',{recursive:true});
  await page.screenshot({path:'assets/screenshots/extracta-desktop.png',fullPage:true});
  await page.locator('#available').check();
  assert.equal(await page.locator('#rows tr').count(),9);
  await page.locator('#filter').fill('Lámpara');
  assert.equal(await page.locator('#rows tr').count(),1);
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#csv').click();
  const download = await downloadPromise;
  const text = await fs.readFile(await download.path(),'utf8');
  assert.match(text,/AT-001/);
  assert(!text.includes('AT-002'));
  await page.locator('#available').uncheck();
  await page.locator('#filter').fill('');
  await page.locator('#item').fill('[');
  await page.locator('#run').click();
  await page.waitForFunction(() => !document.querySelector('#run').disabled);
  assert.match(await page.locator('#summary').textContent(), /Selector inválido/);
  assert(await page.locator('#csv').isDisabled());
  await page.locator('#reset').click();
  await page.locator('#pages').selectOption('1');
  await page.locator('#run').click();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '4');
  assert.match(await page.locator('#summary').textContent(), /límite de páginas/);
  await page.locator('#sourceMode').selectOption('paste');
  await page.locator('#customHtml').fill('<article class="product"><h2>&lt;script&gt;alert(1)&lt;/script&gt;</h2><span class="sku">=HYPERLINK("test")</span><span class="price">$1.20</span><span class="stock">2</span><span class="category">Prueba</span></article>');
  await page.locator('#run').click();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '1');
  assert.match(await page.locator('#rows').textContent(), /<script>alert\(1\)<\/script>/);
  assert.equal(await page.locator('#rows script').count(),0);
  const csvPromise = page.waitForEvent('download');
  await page.locator('#csv').click();
  const customCsv = await fs.readFile(await (await csvPromise).path(),'utf8');
  assert(customCsv.includes("'=HYPERLINK"));
  await page.locator('#sourceMode').selectOption('fixture');
  await page.locator('#pages').selectOption('3');
  await page.locator('#run').click();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '10');
  await page.setViewportSize({width:1800,height:1350});
  await page.evaluate(() => {window.scrollTo(0,0); document.querySelector('.table-wrap').scrollTop = 0;});
  await page.screenshot({path:'assets/screenshots/extracta-upwork-4x3.png',fullPage:false});
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(() => document.querySelector('.config details').open = false);
  await page.evaluate(() => {window.scrollTo(0,0); document.querySelector('.table-wrap').scrollTop = 0;});
  await page.screenshot({path:'assets/screenshots/extracta-mobile.png',fullPage:true});
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.deepEqual(errors,[]);
  console.log('PASS: 3-page extraction, quality report, filtering, CSV download, invalid selectors, limits, custom HTML, XSS-safe text, CSV formula protection, mobile overflow.');
  await browser.close();
})().catch(e => {console.error(e);process.exit(1)});
