const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const python = process.env.PIPELINE_PYTHON || (process.platform === 'win32' ? '.venv/Scripts/python.exe' : 'python3');
async function jsonDownload(page) {
  const event = page.waitForEvent('download'); await page.locator('#json').click();
  return JSON.parse(await fs.readFile(await (await event).path(),'utf8'));
}
function normalize(rows) {return rows.map(row => ({...row, source: row.source.split('/').pop()}));}
(async () => {
  const browser = await chromium.launch({headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:1080},deviceScaleFactor:1});
  const page = await context.newPage(), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.DEMO_URL || 'http://127.0.0.1:5083');
  await page.locator('#run').click();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '162');
  assert.equal(await page.locator('#rows tr').count(),162);
  assert(!/Adultos|Niños/.test(await page.locator('#rows').textContent()));
  assert.equal(await page.locator('#rows td[data-field="record_type"]').filter({hasText:'Adicional'}).count(),2);
  assert.equal(await page.locator('#rows td[data-field="record_type"]').filter({hasText:'Bebida'}).count(),160);
  assert(await page.locator('#stockFilter').isHidden());
  assert.equal(await page.locator('#stock').count(),0);
  assert(await page.locator('#tableNote').textContent().then(text => text.includes('locales')));
  await page.locator('#scope').selectOption('rates');
  assert.equal(await page.locator('#rows tr').count(),2);
  assert.deepEqual(await page.locator('#rows td[data-field="name"]').allTextContents(),['Adultos','Niños']);
  assert.deepEqual((await jsonDownload(page)).rows.map(row => row.price),[99,46]);
  assert.equal(await page.locator('#tableHead').getByText('Producto',{exact:true}).count(),0);
  await page.locator('#scope').selectOption('all');
  const all = await jsonDownload(page); assert.equal(all.rows.length,164);
  execFileSync(python,['pipeline.py','--scope','all','--output','output/browser-reference'],{stdio:'pipe'});
  const cli = JSON.parse(await fs.readFile('output/browser-reference/report.json','utf8'));
  assert.deepEqual(normalize(all.rows),normalize(cli.rows));
  await page.locator('#scope').selectOption('items');
  await page.locator('#goal').selectOption('categories');
  const categories = await jsonDownload(page);
  assert.equal(categories.rows.reduce((n,row) => n+row.item_count,0),162);
  assert(categories.rows.every(row => row.min_price <= row.max_price));
  assert(!categories.rows.some(row => row.category === 'Tarifas buffet'));
  await page.locator('#goal').selectOption('prices');
  assert.equal(await page.locator('#tableHead th[data-field="description"]').count(),0);
  await page.locator('#priority').selectOption('price');
  const prices = (await jsonDownload(page)).rows;
  assert(prices.every((row,i) => i === 0 || row.price >= prices[i-1].price));
  await page.locator('#fieldChoices input[value="price"]').uncheck();
  assert(!(await jsonDownload(page)).rows.some(row => 'price' in row));
  while (await page.locator('#fieldChoices input:checked').count()) await page.locator('#fieldChoices input:checked').first().uncheck();
  assert(await page.locator('#csv').isDisabled());
  assert.match(await page.locator('#rows').textContent(),/al menos una columna/);
  await page.locator('#goal').selectOption('detail'); await page.locator('#priority').selectOption('source');
  await page.locator('#run').click(); await page.waitForFunction(() => document.querySelector('#count').textContent === '162');
  await fs.mkdir('assets/screenshots',{recursive:true});
  await page.screenshot({path:'assets/screenshots/enybyy-extract-desktop.png',fullPage:true});
  await page.locator('#html').click();
  const markup = await page.locator('#sourceHtml').textContent(); assert(markup.includes('  <head>'));
  assert(!/Adultos|Niños/.test(await page.locator('#rows').textContent()));
  assert(markup.includes('class="record-type"')); assert(await page.locator('#sourceHtml .code-tag').count()>100);
  await page.screenshot({path:'assets/screenshots/enybyy-extract-html.png',fullPage:true});
  await page.locator('#visual').click();
  await page.setViewportSize({width:1800,height:1350}); await page.screenshot({path:'assets/screenshots/enybyy-extract-upwork-4x3.png'});
  await page.setViewportSize({width:390,height:844}); await page.screenshot({path:'assets/screenshots/enybyy-extract-mobile.png',fullPage:true});
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.setViewportSize({width:1440,height:1080});
  await page.locator('#sourceMode').selectOption('fixture');
  assert.equal(await page.locator('#record_type').count(),0); assert.equal(await page.locator('#stock').inputValue(),'.stock');
  assert.equal(await page.locator('#scope option[value="rates"]').count(),0);
  await page.locator('#run').click(); await page.waitForFunction(() => document.querySelector('#count').textContent === '10');
  assert.match(await page.locator('#summary').textContent(),/3 páginas.*1 duplicados.*1 incompletos/);
  execFileSync(python,['pipeline.py','--source',require('node:url').pathToFileURL(path.resolve('fixtures/catalog-1.html')).href,'--schema','catalog-schema.json','--scope','all','--output','output/browser-reference-catalog'],{stdio:'pipe'});
  const catalogCli = JSON.parse(await fs.readFile('output/browser-reference-catalog/report.json','utf8'));
  assert.deepEqual(normalize((await jsonDownload(page)).rows),normalize(catalogCli.rows));
  assert.match(await page.locator('#tableHead th[data-field="price"]').textContent(),/USD/);
  await page.screenshot({path:'assets/screenshots/enybyy-extract-catalog.png',fullPage:true});
  await page.locator('#goal').selectOption('categories');
  assert.equal((await jsonDownload(page)).rows.reduce((n,row) => n+row.item_count,0),10);
  await page.locator('#goal').selectOption('prices');
  assert.deepEqual(Object.keys((await jsonDownload(page)).rows[0]),['name','category','price']);
  await page.locator('#goal').selectOption('detail');
  await page.locator('#available').check(); assert.equal(await page.locator('#rows tr').count(),9);
  await page.locator('#filter').fill('Lámpara'); assert.equal(await page.locator('#rows tr').count(),1);
  const csvEvent = page.waitForEvent('download'); await page.locator('#csv').click();
  const csv = await fs.readFile(await (await csvEvent).path(),'utf8'); assert(csv.includes('AT-001')); assert(!csv.includes('AT-002'));
  await page.locator('#available').uncheck(); await page.locator('#filter').fill('');
  await page.locator('.selector-options').evaluate(node => node.open = true);
  await page.locator('#item').fill('['); await page.locator('#run').click();
  await page.waitForFunction(() => !document.querySelector('#run').disabled);
  assert.match(await page.locator('#summary').textContent(),/Selector inválido/); assert(await page.locator('#csv').isDisabled());
  await page.locator('#reset').click(); await page.locator('#pages').selectOption('1'); await page.locator('#run').click();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '4'); assert.match(await page.locator('#summary').textContent(),/límite de páginas/);
  await page.locator('#sourceMode').selectOption('paste');
  await page.locator('#customHtml').fill('<article class="product"><h2>&lt;script&gt;alert(1)&lt;/script&gt;</h2><span class="sku">=HYPERLINK("test")</span><span class="price">$1.20</span><span class="stock">2</span><span class="category">Prueba</span></article>');
  await page.locator('#run').click(); await page.waitForFunction(() => document.querySelector('#count').textContent === '1');
  assert.match(await page.locator('#rows').textContent(),/<script>alert\(1\)<\/script>/); assert.equal(await page.locator('#rows script').count(),0);
  const customCsvEvent = page.waitForEvent('download'); await page.locator('#csv').click();
  assert((await fs.readFile(await (await customCsvEvent).path(),'utf8')).includes("'=HYPERLINK"));
  await page.locator('#sourceMode').selectOption('menu');
  assert.equal(await page.locator('#record_type').inputValue(),'.record-type'); assert.equal(await page.locator('#stock').count(),0);
  await page.locator('#run').click(); await page.waitForFunction(() => document.querySelector('#count').textContent === '162');
  assert(!/Adultos|Niños/.test(await page.locator('#rows').textContent()));
  const source = await context.newPage(); await source.goto((process.env.DEMO_URL || 'http://127.0.0.1:5083')+'/fixtures/menu.html');
  await source.setViewportSize({width:1100,height:1050}); await source.screenshot({path:'assets/screenshots/enybyy-extract-menu.png'});
  await source.setViewportSize({width:360,height:800}); assert(await source.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.deepEqual(errors,[]);
  console.log('PASS: all 164 menu and 10 catalog records match Python; tariff separation, output modes, selected columns, price sorting, exports, selectors, pagination, custom HTML and mobile.');
  await browser.close();
})().catch(error => {console.error(error); process.exit(1);});
